### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by ata-o** [CankayaUniversity/ceng-407-408-An-SaaS-Platform-for-Ridesharing-Taxi-Cab-Food-Delivery-and-Shipping#7]
A user manual is needed for senior project delivery.

**Comment by onuratasaritas** [comment]
User manual structure created, see [link](https://github.com/CankayaUniversity/ceng-407-408-An-SaaS-Platform-for-Ridesharing-Taxi-Cab-Food-Delivery-and-Shipping/wiki/User-Manual). Screenshots from latest build needed.

**Comment by onuratasaritas** [comment]
Finished the user manual. Report for the senior project delivery will be available soon.
